
$FirebaseSDKVersion = '7.0.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
pod 'Firebase/Auth'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'etrip_v1' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'etrip_v1Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'etrip_v1-tvOS' do
  # Pods for etrip_v1-tvOS

  target 'etrip_v1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
